/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.codekata.cloudkeytool;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    App app = new App();
    assertNotNull(app, "app should have a greeting");
  }
}
